"""Shared wire-format constants for benchmark and quality evidence."""

SHA256_HEX_LENGTH = 64
GIT_SHA1_HEX_LENGTH = 40
LOWERCASE_HEX_DIGITS = frozenset("0123456789abcdef")
RGB_CHANNEL_COUNT = 3
UINT8_CHANNEL_MAX = 255
COMPUTE_CAPABILITY_COMPONENT_COUNT = 2
PERCENTAGE_POINTS_SCALE = 100.0
DECODE_COMPILE_SUBGRAPH = "qkv_projection_qk_norm_mrope"
DECODE_COMPILE_STATELESS_SUBGRAPH = (
    "batch1_o_proj_fp8_candidate_lm_head_exact_rerank"
)
DECODE_COMPILE_KV_BOUNDARY = "validated_runtime_store_and_paged_decode"


__all__ = [
    "COMPUTE_CAPABILITY_COMPONENT_COUNT",
    "DECODE_COMPILE_KV_BOUNDARY",
    "DECODE_COMPILE_STATELESS_SUBGRAPH",
    "DECODE_COMPILE_SUBGRAPH",
    "GIT_SHA1_HEX_LENGTH",
    "LOWERCASE_HEX_DIGITS",
    "PERCENTAGE_POINTS_SCALE",
    "RGB_CHANNEL_COUNT",
    "SHA256_HEX_LENGTH",
    "UINT8_CHANNEL_MAX",
]
